parameters:
- name: gubun
  displayName: Environment (for ITSM)
  type: string
  default: environment
- name: KEY
  displayName: Branch (for ITSM)
  type: string
  default: Branch
# TEMPORARY AZURE ACCESS TOKEN :: START
# Remove this parameter after Service Principal authentication is enabled.
- name: azure_access_token
  displayName: Azure Resource Manager access token
  type: string
  default: '__NOT_PROVIDED__'
# TEMPORARY AZURE ACCESS TOKEN :: END
trigger: none

variables:
- name: imageTag
  value: ${{ parameters.KEY }}

stages:
- stage: CD
  displayName: CD stage Dev ENV
  jobs:
  - deployment: Deploy
    displayName: Deploy App Service container
    environment: app-service-np
    # TEMPORARY AZURE ACCESS TOKEN :: START
    # Remove this condition after Service Principal authentication is enabled.
    condition: and(succeeded(), ne('${{ parameters.azure_access_token }}', '__NOT_PROVIDED__'), ne('${{ parameters.azure_access_token }}', ''))
    # TEMPORARY AZURE ACCESS TOKEN :: END
    timeoutInMinutes: '40'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: templates/app-service-deploy.yml
            parameters:
              # TEMPORARY AZURE ACCESS TOKEN :: START
              # Remove this mapping after Service Principal authentication is enabled.
              azure_access_token: ${{ parameters.azure_access_token }}
              # TEMPORARY AZURE ACCESS TOKEN :: END
              timeout_in_minutes: 10
              subscription_id: 'd423337a-8a9a-43fd-891c-4f57161bc69d'
              resource_group: 'RG_00001_Public-App-Service_DV01'
              app_type: 'Function App'
              app_name: 'fpy00001kcdv0101'
              acr_name: 'acr00001kcdv0101'
              image_name: 'document-vectorizer-function-app'
              image_tag: $(imageTag)
